### ISSUE TITLE
InfluxDB v2 Tag 

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#42]
Apparently, the current DSL implementation does not support Influxdb v2 and does not support custom TAG pushing. 
![image](https://user-images.githubusercontent.com/9977326/141110035-6697dc6d-a3bb-4e26-bc28-c65488687019.png)
Can you add this feature?

**Comment by rabelenda** [comment]
Why do you say that current DSL does not support InfluxDB v2? What is it that you are experiencing?

I just tried with v2 influxdb and is working for a simple use case.

For instance I see data in grafana when using files included [here](https://github.com/abstracta/jmeter-java-dsl/tree/master/docs/guide/influxdb) but with following changes:

```yaml
version: '3'
services:
  influxdb:
    image: influxdb:2.0
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb
      - ./influxdb-provisioning/:/docker-entrypoint-initdb.d
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=administrator
      - DOCKER_INFLUXDB_INIT_ORG=abstracta
      - DOCKER_INFLUXDB_INIT_BUCKET=jmeter
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=supersecrettoken
      - V1_DB_NAME=jmeter
      - V1_RP_NAME=jmeter
  grafana:
    image: grafana/grafana:8.1.7
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=1234
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/jmeter.json
volumes:
  influxdb-data:
  grafana-data:
```

add a `setup.sh` file inside new `influxdb-provisioning` folder with this content:

```shell
#!/bin/bash
set -e

influx v1 dbrp create \
  --bucket-id ${DOCKER_INFLUXDB_INIT_BUCKET_ID} \
  --db ${V1_DB_NAME} \
  --rp ${V1_RP_NAME} \
  --default \
  --org ${DOCKER_INFLUXDB_INIT_ORG}
```

Open graphana and change datasource, clearing user and password and adding an http header with `Authorization: Token supersecrettoken`

Test plan with listener configured like this:

```java
influxDbListener("http://localhost:8086/api/v2/write?org=abstracta&bucket=jmeter")
              .token("supersecrettoken")
```
